export interface CityDestination {
	id: string;
	name: string;
	country: string;
	region: string;
	coords: [number, number];
	distanceKm?: number;
}

export const BOKARO_COORDS: [number, number] = [23.6693, 86.1511];

export const INDIAN_CITIES: CityDestination[] = [
	{
		id: "delhi",
		name: "Delhi",
		country: "India",
		region: "India",
		coords: [28.6139, 77.209],
	},
	{
		id: "mumbai",
		name: "Mumbai",
		country: "India",
		region: "India",
		coords: [19.076, 72.8777],
	},
	{
		id: "kolkata",
		name: "Kolkata",
		country: "India",
		region: "India",
		coords: [22.5726, 88.3639],
	},
	{
		id: "chennai",
		name: "Chennai",
		country: "India",
		region: "India",
		coords: [13.0827, 80.2707],
	},
	{
		id: "bangalore",
		name: "Bangalore",
		country: "India",
		region: "India",
		coords: [12.9716, 77.5946],
	},
	{
		id: "hyderabad",
		name: "Hyderabad",
		country: "India",
		region: "India",
		coords: [17.385, 78.4867],
	},
	{
		id: "pune",
		name: "Pune",
		country: "India",
		region: "India",
		coords: [18.5204, 73.8567],
	},
	{
		id: "ahmedabad",
		name: "Ahmedabad",
		country: "India",
		region: "India",
		coords: [23.0225, 72.5714],
	},
	{
		id: "jaipur",
		name: "Jaipur",
		country: "India",
		region: "India",
		coords: [26.9124, 75.7873],
	},
	{
		id: "lucknow",
		name: "Lucknow",
		country: "India",
		region: "India",
		coords: [26.8467, 80.9462],
	},
	{
		id: "ranchi",
		name: "Ranchi",
		country: "India",
		region: "India",
		coords: [23.3441, 85.3095],
	},
	{
		id: "jamshedpur",
		name: "Jamshedpur",
		country: "India",
		region: "India",
		coords: [22.8046, 86.1853],
	},
	{
		id: "patna",
		name: "Patna",
		country: "India",
		region: "India",
		coords: [25.5941, 85.1376],
	},
	{
		id: "bhubaneswar",
		name: "Bhubaneswar",
		country: "India",
		region: "India",
		coords: [20.2961, 85.8245],
	},
	{
		id: "varanasi",
		name: "Varanasi",
		country: "India",
		region: "India",
		coords: [25.3176, 82.9739],
	},
	{
		id: "allahabad",
		name: "Prayagraj",
		country: "India",
		region: "India",
		coords: [25.4358, 81.8463],
	},
	{
		id: "kanpur",
		name: "Kanpur",
		country: "India",
		region: "India",
		coords: [26.4499, 80.3319],
	},
	{
		id: "nagpur",
		name: "Nagpur",
		country: "India",
		region: "India",
		coords: [21.1458, 79.0882],
	},
	{
		id: "indore",
		name: "Indore",
		country: "India",
		region: "India",
		coords: [22.7196, 75.8577],
	},
	{
		id: "bhopal",
		name: "Bhopal",
		country: "India",
		region: "India",
		coords: [23.2599, 77.4126],
	},
	{
		id: "chandigarh",
		name: "Chandigarh",
		country: "India",
		region: "India",
		coords: [30.7333, 76.7794],
	},
	{
		id: "dehradun",
		name: "Dehradun",
		country: "India",
		region: "India",
		coords: [30.3165, 78.0322],
	},
	{
		id: "shimla",
		name: "Shimla",
		country: "India",
		region: "India",
		coords: [31.1048, 77.1734],
	},
	{
		id: "gangtok",
		name: "Gangtok",
		country: "India",
		region: "India",
		coords: [27.3389, 88.6065],
	},
	{
		id: "guwahati",
		name: "Guwahati",
		country: "India",
		region: "India",
		coords: [26.1445, 91.7362],
	},
	{
		id: "shillong",
		name: "Shillong",
		country: "India",
		region: "India",
		coords: [25.5788, 91.8933],
	},
	{
		id: "kochi",
		name: "Kochi",
		country: "India",
		region: "India",
		coords: [9.9312, 76.2673],
	},
	{
		id: "thiruvananthapuram",
		name: "Thiruvananthapuram",
		country: "India",
		region: "India",
		coords: [8.5241, 76.9366],
	},
	{
		id: "coimbatore",
		name: "Coimbatore",
		country: "India",
		region: "India",
		coords: [11.0168, 76.9558],
	},
	{
		id: "madurai",
		name: "Madurai",
		country: "India",
		region: "India",
		coords: [9.9252, 78.1198],
	},
	{
		id: "visakhapatnam",
		name: "Visakhapatnam",
		country: "India",
		region: "India",
		coords: [17.6868, 83.2185],
	},
	{
		id: "vijayawada",
		name: "Vijayawada",
		country: "India",
		region: "India",
		coords: [16.5062, 80.648],
	},
	{
		id: "agra",
		name: "Agra",
		country: "India",
		region: "India",
		coords: [27.1767, 78.0081],
	},
	{
		id: "mathura",
		name: "Mathura",
		country: "India",
		region: "India",
		coords: [27.4924, 77.6737],
	},
	{
		id: "haridwar",
		name: "Haridwar",
		country: "India",
		region: "India",
		coords: [29.9457, 78.1642],
	},
	{
		id: "rishikesh",
		name: "Rishikesh",
		country: "India",
		region: "India",
		coords: [30.0869, 78.2676],
	},
	{
		id: "amritsar",
		name: "Amritsar",
		country: "India",
		region: "India",
		coords: [31.634, 74.8723],
	},
	{
		id: "ludhiana",
		name: "Ludhiana",
		country: "India",
		region: "India",
		coords: [30.9009, 75.8573],
	},
	{
		id: "jammu",
		name: "Jammu",
		country: "India",
		region: "India",
		coords: [32.7266, 74.857],
	},
	{
		id: "srinagar",
		name: "Srinagar",
		country: "India",
		region: "India",
		coords: [34.0837, 74.7973],
	},
	{
		id: "surat",
		name: "Surat",
		country: "India",
		region: "India",
		coords: [21.1702, 72.8311],
	},
	{
		id: "vadodara",
		name: "Vadodara",
		country: "India",
		region: "India",
		coords: [22.3072, 73.1812],
	},
	{
		id: "nashik",
		name: "Nashik",
		country: "India",
		region: "India",
		coords: [19.9975, 73.7898],
	},
	{
		id: "mangalore",
		name: "Mangalore",
		country: "India",
		region: "India",
		coords: [12.9141, 74.856],
	},
	{
		id: "mysore",
		name: "Mysore",
		country: "India",
		region: "India",
		coords: [12.2958, 76.6394],
	},
	{
		id: "goa",
		name: "Goa",
		country: "India",
		region: "India",
		coords: [15.2993, 74.124],
	},
	{
		id: "udaipur",
		name: "Udaipur",
		country: "India",
		region: "India",
		coords: [24.5854, 73.7125],
	},
	{
		id: "jodhpur",
		name: "Jodhpur",
		country: "India",
		region: "India",
		coords: [26.2389, 73.0243],
	},
	{
		id: "kota",
		name: "Kota",
		country: "India",
		region: "India",
		coords: [25.2138, 75.8648],
	},
	{
		id: "raipur",
		name: "Raipur",
		country: "India",
		region: "India",
		coords: [21.2514, 81.6296],
	},
];

export const ASIAN_CITIES: CityDestination[] = [
	{
		id: "beijing",
		name: "Beijing",
		country: "China",
		region: "Asia",
		coords: [39.9042, 116.4074],
	},
	{
		id: "shanghai",
		name: "Shanghai",
		country: "China",
		region: "Asia",
		coords: [31.2304, 121.4737],
	},
	{
		id: "hongkong",
		name: "Hong Kong",
		country: "China",
		region: "Asia",
		coords: [22.3193, 114.1694],
	},
	{
		id: "tokyo",
		name: "Tokyo",
		country: "Japan",
		region: "Asia",
		coords: [35.6762, 139.6503],
	},
	{
		id: "osaka",
		name: "Osaka",
		country: "Japan",
		region: "Asia",
		coords: [34.6937, 135.5023],
	},
	{
		id: "seoul",
		name: "Seoul",
		country: "South Korea",
		region: "Asia",
		coords: [37.5665, 126.978],
	},
	{
		id: "singapore",
		name: "Singapore",
		country: "Singapore",
		region: "Asia",
		coords: [1.3521, 103.8198],
	},
	{
		id: "bangkok",
		name: "Bangkok",
		country: "Thailand",
		region: "Asia",
		coords: [13.7563, 100.5018],
	},
	{
		id: "hanoi",
		name: "Hanoi",
		country: "Vietnam",
		region: "Asia",
		coords: [21.0285, 105.8542],
	},
	{
		id: "hochiminh",
		name: "Ho Chi Minh City",
		country: "Vietnam",
		region: "Asia",
		coords: [10.8231, 106.6297],
	},
	{
		id: "dubai",
		name: "Dubai",
		country: "UAE",
		region: "Asia",
		coords: [25.2048, 55.2708],
	},
	{
		id: "abudhabi",
		name: "Abu Dhabi",
		country: "UAE",
		region: "Asia",
		coords: [24.4539, 54.3773],
	},
	{
		id: "doha",
		name: "Doha",
		country: "Qatar",
		region: "Asia",
		coords: [25.2854, 51.531],
	},
	{
		id: "istanbul",
		name: "Istanbul",
		country: "Turkey",
		region: "Asia",
		coords: [41.0082, 28.9784],
	},
	{
		id: "tehran",
		name: "Tehran",
		country: "Iran",
		region: "Asia",
		coords: [35.6892, 51.389],
	},
	{
		id: "riyadh",
		name: "Riyadh",
		country: "Saudi Arabia",
		region: "Asia",
		coords: [24.7136, 46.6753],
	},
	{
		id: "jeddah",
		name: "Jeddah",
		country: "Saudi Arabia",
		region: "Asia",
		coords: [21.4858, 39.1925],
	},
	{
		id: "kathmandu",
		name: "Kathmandu",
		country: "Nepal",
		region: "Asia",
		coords: [27.7172, 85.324],
	},
	{
		id: "colombo",
		name: "Colombo",
		country: "Sri Lanka",
		region: "Asia",
		coords: [6.9271, 79.8612],
	},
	{
		id: "dhaka",
		name: "Dhaka",
		country: "Bangladesh",
		region: "Asia",
		coords: [23.8103, 90.4125],
	},
	{
		id: "jakarta",
		name: "Jakarta",
		country: "Indonesia",
		region: "Asia",
		coords: [-6.2088, 106.8456],
	},
	{
		id: "bali",
		name: "Bali",
		country: "Indonesia",
		region: "Asia",
		coords: [-8.3405, 115.092],
	},
	{
		id: "manila",
		name: "Manila",
		country: "Philippines",
		region: "Asia",
		coords: [14.5995, 120.9842],
	},
	{
		id: "kualalumpur",
		name: "Kuala Lumpur",
		country: "Malaysia",
		region: "Asia",
		coords: [3.139, 101.6869],
	},
	{
		id: "yangon",
		name: "Yangon",
		country: "Myanmar",
		region: "Asia",
		coords: [16.8661, 96.1951],
	},
	{
		id: "taipei",
		name: "Taipei",
		country: "Taiwan",
		region: "Asia",
		coords: [25.033, 121.5654],
	},
	{
		id: "shenzhen",
		name: "Shenzhen",
		country: "China",
		region: "Asia",
		coords: [22.5431, 114.0579],
	},
	{
		id: "guangzhou",
		name: "Guangzhou",
		country: "China",
		region: "Asia",
		coords: [23.1291, 113.2644],
	},
	{
		id: "chengdu",
		name: "Chengdu",
		country: "China",
		region: "Asia",
		coords: [30.5728, 104.0668],
	},
	{
		id: "xian",
		name: "Xi'an",
		country: "China",
		region: "Asia",
		coords: [34.3416, 108.9398],
	},
];

export const EUROPEAN_CITIES: CityDestination[] = [
	{
		id: "london",
		name: "London",
		country: "UK",
		region: "Europe",
		coords: [51.5074, -0.1278],
	},
	{
		id: "paris",
		name: "Paris",
		country: "France",
		region: "Europe",
		coords: [48.8566, 2.3522],
	},
	{
		id: "berlin",
		name: "Berlin",
		country: "Germany",
		region: "Europe",
		coords: [52.52, 13.405],
	},
	{
		id: "rome",
		name: "Rome",
		country: "Italy",
		region: "Europe",
		coords: [41.9028, 12.4964],
	},
	{
		id: "madrid",
		name: "Madrid",
		country: "Spain",
		region: "Europe",
		coords: [40.4168, -3.7038],
	},
	{
		id: "amsterdam",
		name: "Amsterdam",
		country: "Netherlands",
		region: "Europe",
		coords: [52.3676, 4.9041],
	},
	{
		id: "brussels",
		name: "Brussels",
		country: "Belgium",
		region: "Europe",
		coords: [50.8503, 4.3517],
	},
	{
		id: "vienna",
		name: "Vienna",
		country: "Austria",
		region: "Europe",
		coords: [48.2082, 16.3738],
	},
	{
		id: "zurich",
		name: "Zurich",
		country: "Switzerland",
		region: "Europe",
		coords: [47.3769, 8.5417],
	},
	{
		id: "munich",
		name: "Munich",
		country: "Germany",
		region: "Europe",
		coords: [48.1351, 11.582],
	},
	{
		id: "frankfurt",
		name: "Frankfurt",
		country: "Germany",
		region: "Europe",
		coords: [50.1109, 8.6821],
	},
	{
		id: "milan",
		name: "Milan",
		country: "Italy",
		region: "Europe",
		coords: [45.4642, 9.19],
	},
	{
		id: "barcelona",
		name: "Barcelona",
		country: "Spain",
		region: "Europe",
		coords: [41.3851, 2.1734],
	},
	{
		id: "lisbon",
		name: "Lisbon",
		country: "Portugal",
		region: "Europe",
		coords: [38.7223, -9.1393],
	},
	{
		id: "prague",
		name: "Prague",
		country: "Czech Republic",
		region: "Europe",
		coords: [50.0755, 14.4378],
	},
	{
		id: "warsaw",
		name: "Warsaw",
		country: "Poland",
		region: "Europe",
		coords: [52.2297, 21.0122],
	},
	{
		id: "budapest",
		name: "Budapest",
		country: "Hungary",
		region: "Europe",
		coords: [47.4979, 19.0402],
	},
	{
		id: "athens",
		name: "Athens",
		country: "Greece",
		region: "Europe",
		coords: [37.9838, 23.7275],
	},
	{
		id: "dublin",
		name: "Dublin",
		country: "Ireland",
		region: "Europe",
		coords: [53.3498, -6.2603],
	},
	{
		id: "copenhagen",
		name: "Copenhagen",
		country: "Denmark",
		region: "Europe",
		coords: [55.6761, 12.5683],
	},
	{
		id: "stockholm",
		name: "Stockholm",
		country: "Sweden",
		region: "Europe",
		coords: [59.3293, 18.0686],
	},
	{
		id: "oslo",
		name: "Oslo",
		country: "Norway",
		region: "Europe",
		coords: [59.9139, 10.7522],
	},
	{
		id: "helsinki",
		name: "Helsinki",
		country: "Finland",
		region: "Europe",
		coords: [60.1699, 24.9384],
	},
	{
		id: "moscow",
		name: "Moscow",
		country: "Russia",
		region: "Europe",
		coords: [55.7558, 37.6173],
	},
	{
		id: "stpetersburg",
		name: "St. Petersburg",
		country: "Russia",
		region: "Europe",
		coords: [59.9343, 30.3351],
	},
	{
		id: "edinburgh",
		name: "Edinburgh",
		country: "UK",
		region: "Europe",
		coords: [55.9533, -3.1883],
	},
	{
		id: "manchester",
		name: "Manchester",
		country: "UK",
		region: "Europe",
		coords: [53.4808, -2.2426],
	},
	{
		id: "lyon",
		name: "Lyon",
		country: "France",
		region: "Europe",
		coords: [45.764, 4.8357],
	},
	{
		id: "marseille",
		name: "Marseille",
		country: "France",
		region: "Europe",
		coords: [43.2965, 5.3698],
	},
];

export const AMERICAS_CITIES: CityDestination[] = [
	{
		id: "newyork",
		name: "New York",
		country: "USA",
		region: "Americas",
		coords: [40.7128, -74.006],
	},
	{
		id: "losangeles",
		name: "Los Angeles",
		country: "USA",
		region: "Americas",
		coords: [34.0522, -118.2437],
	},
	{
		id: "chicago",
		name: "Chicago",
		country: "USA",
		region: "Americas",
		coords: [41.8781, -87.6298],
	},
	{
		id: "sanfrancisco",
		name: "San Francisco",
		country: "USA",
		region: "Americas",
		coords: [37.7749, -122.4194],
	},
	{
		id: "miami",
		name: "Miami",
		country: "USA",
		region: "Americas",
		coords: [25.7617, -80.1918],
	},
	{
		id: "seattle",
		name: "Seattle",
		country: "USA",
		region: "Americas",
		coords: [47.6062, -122.3321],
	},
	{
		id: "boston",
		name: "Boston",
		country: "USA",
		region: "Americas",
		coords: [42.3601, -71.0589],
	},
	{
		id: "denver",
		name: "Denver",
		country: "USA",
		region: "Americas",
		coords: [39.7392, -104.9903],
	},
	{
		id: "atlanta",
		name: "Atlanta",
		country: "USA",
		region: "Americas",
		coords: [33.749, -84.388],
	},
	{
		id: "dallas",
		name: "Dallas",
		country: "USA",
		region: "Americas",
		coords: [32.7767, -96.797],
	},
	{
		id: "houston",
		name: "Houston",
		country: "USA",
		region: "Americas",
		coords: [29.7604, -95.3698],
	},
	{
		id: "phoenix",
		name: "Phoenix",
		country: "USA",
		region: "Americas",
		coords: [33.4484, -112.074],
	},
	{
		id: "lasvegas",
		name: "Las Vegas",
		country: "USA",
		region: "Americas",
		coords: [36.1699, -115.1398],
	},
	{
		id: "toronto",
		name: "Toronto",
		country: "Canada",
		region: "Americas",
		coords: [43.6532, -79.3832],
	},
	{
		id: "vancouver",
		name: "Vancouver",
		country: "Canada",
		region: "Americas",
		coords: [49.2827, -123.1207],
	},
	{
		id: "montreal",
		name: "Montreal",
		country: "Canada",
		region: "Americas",
		coords: [45.5017, -73.5673],
	},
	{
		id: "mexicocity",
		name: "Mexico City",
		country: "Mexico",
		region: "Americas",
		coords: [19.4326, -99.1332],
	},
	{
		id: "saopaulo",
		name: "Sao Paulo",
		country: "Brazil",
		region: "Americas",
		coords: [-23.5505, -46.6333],
	},
	{
		id: "rio",
		name: "Rio de Janeiro",
		country: "Brazil",
		region: "Americas",
		coords: [-22.9068, -43.1729],
	},
	{
		id: "buenosaires",
		name: "Buenos Aires",
		country: "Argentina",
		region: "Americas",
		coords: [-34.6037, -58.3816],
	},
	{
		id: "lima",
		name: "Lima",
		country: "Peru",
		region: "Americas",
		coords: [-12.0464, -77.0428],
	},
	{
		id: "santiago",
		name: "Santiago",
		country: "Chile",
		region: "Americas",
		coords: [-33.4489, -70.6693],
	},
	{
		id: "bogota",
		name: "Bogota",
		country: "Colombia",
		region: "Americas",
		coords: [4.711, -74.0721],
	},
	{
		id: "caracas",
		name: "Caracas",
		country: "Venezuela",
		region: "Americas",
		coords: [10.4806, -66.9036],
	},
];

export const OTHERS_CITIES: CityDestination[] = [
	{
		id: "sydney",
		name: "Sydney",
		country: "Australia",
		region: "Oceania",
		coords: [-33.8688, 151.2093],
	},
	{
		id: "melbourne",
		name: "Melbourne",
		country: "Australia",
		region: "Oceania",
		coords: [-37.8136, 144.9631],
	},
	{
		id: "brisbane",
		name: "Brisbane",
		country: "Australia",
		region: "Oceania",
		coords: [-27.4698, 153.0251],
	},
	{
		id: "perth",
		name: "Perth",
		country: "Australia",
		region: "Oceania",
		coords: [-31.9505, 115.8605],
	},
	{
		id: "auckland",
		name: "Auckland",
		country: "New Zealand",
		region: "Oceania",
		coords: [-36.8485, 174.7633],
	},
	{
		id: "wellington",
		name: "Wellington",
		country: "New Zealand",
		region: "Oceania",
		coords: [-41.2865, 174.7762],
	},
	{
		id: "capetown",
		name: "Cape Town",
		country: "South Africa",
		region: "Africa",
		coords: [-33.9249, 18.4241],
	},
	{
		id: "johannesburg",
		name: "Johannesburg",
		country: "South Africa",
		region: "Africa",
		coords: [-26.2041, 28.0473],
	},
	{
		id: "durban",
		name: "Durban",
		country: "South Africa",
		region: "Africa",
		coords: [-29.8587, 31.0218],
	},
	{
		id: "cairo",
		name: "Cairo",
		country: "Egypt",
		region: "Africa",
		coords: [30.0444, 31.2357],
	},
	{
		id: "lagos",
		name: "Lagos",
		country: "Nigeria",
		region: "Africa",
		coords: [6.5244, 3.3792],
	},
	{
		id: "nairobi",
		name: "Nairobi",
		country: "Kenya",
		region: "Africa",
		coords: [-1.2921, 36.8219],
	},
	{
		id: "casablanca",
		name: "Casablanca",
		country: "Morocco",
		region: "Africa",
		coords: [33.5731, -7.5898],
	},
	{
		id: "tunis",
		name: "Tunis",
		country: "Tunisia",
		region: "Africa",
		coords: [36.8065, 10.1815],
	},
	{
		id: "addisababa",
		name: "Addis Ababa",
		country: "Ethiopia",
		region: "Africa",
		coords: [8.9806, 38.7578],
	},
];

export const ALL_DESTINATIONS: CityDestination[] = [
	...INDIAN_CITIES,
	...ASIAN_CITIES,
	...EUROPEAN_CITIES,
	...AMERICAS_CITIES,
	...OTHERS_CITIES,
];

export function searchCities(query: string): CityDestination[] {
	const q = query.toLowerCase().trim();
	if (!q) return [];
	return ALL_DESTINATIONS.filter(
		(c) =>
			c.name.toLowerCase().includes(q) ||
			c.country.toLowerCase().includes(q) ||
			c.region.toLowerCase().includes(q),
	).slice(0, 10);
}

export function getCitiesByRegion(): Record<string, CityDestination[]> {
	return {
		India: INDIAN_CITIES,
		Asia: ASIAN_CITIES,
		Europe: EUROPEAN_CITIES,
		Americas: AMERICAS_CITIES,
		"Oceania & Africa": OTHERS_CITIES,
	};
}
